name: Build ZMK Firmware

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board:
          - xiao_ble  # Updated board name for Seeed Studio Xiao BLE

    steps:
    - uses: actions/checkout@v2

    - name: Set up Zephyr environment
      run: |
        pip install west
        west init -l app/
        west update
        west zephyr-export

    - name: Build firmware
      run: |
        west build -b ${{ matrix.board }} -d build -- -DZMK_CONFIG=./config
      env:
        ZEPHYR_TOOLCHAIN_VARIANT: zephyr
        ZEPHYR_SDK_INSTALL_DIR: $HOME/zephyr-sdk

    - name: Convert to UF2
      run: |
        pip install uf2tool
        uf2conv.py build/zephyr/zephyr.bin --family 0xADA52840 --output firmware.uf2

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: firmware-uf2
        path: build/zephyr/firmware.uf2
